import { registerEnumType } from '@nestjs/graphql';

export enum BadgeType {
    TRUSTED_BUYER = "TRUSTED_BUYER",
    TRUSTED_SELLER = "TRUSTED_SELLER",
    COMPANY_PICTURE = "COMPANY_PICTURE",
    PERSONAL_REGISTRATION = "PERSONAL_REGISTRATION",
    PERSONAL_SEVI_VERIFICATION_TEAM = "PERSONAL_SEVI_VERIFICATION_TEAM",
    PERSONAL_EMAIL_VERIFIED = "PERSONAL_EMAIL_VERIFIED",
    PERSONAL_TAX_ID = "PERSONAL_TAX_ID",
    MEMBERSHIP_FIRST_MONTH = "MEMBERSHIP_FIRST_MONTH",
    MEMBERSHIP_YEAR = "MEMBERSHIP_YEAR",
    FIRST_ORDER = "FIRST_ORDER",
    SHIPPING_LOCATION = "SHIPPING_LOCATION",
    SETTLEMENT_KES_BANK = "SETTLEMENT_KES_BANK",
    SETTLEMENT_KES_MPESA = "SETTLEMENT_KES_MPESA",
    SELLERS_DOCUMENTS_UPLOADED = "SELLERS_DOCUMENTS_UPLOADED",
    PERSONAL_SEVI_TEAM = "PERSONAL_SEVI_TEAM",
    MPESA_STATEMENT = "MPESA_STATEMENT",
    BANK_STATEMENT = "BANK_STATEMENT",
    BUYER_SHARED_CONTACTS = "BUYER_SHARED_CONTACTS"
}


registerEnumType(BadgeType, { name: 'BadgeType', description: undefined })
