version: '3.9'

services:
  leviticus:
    container_name: leviticus
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.development
    ports:
      - 8001:7000
    # depends_on:
    #   - kibana
    networks:
      - shared-nw
    env_file:
      - ../.env.docker
    volumes:
      - ../src:/app/src:cached
      - ../prisma:/app/prisma:cached
      - ../input:/app/input:cached
      - ../output:/app/output:cached
  # kibana:
  #   container_name: kibana
  #   image: docker.elastic.co/kibana/kibana:8.1.0
  #   environment:
  #     SERVER_NAME: localhost
  #     ELASTICSEARCH_URL: http://elasticsearch1:9200/
  #   networks:
  #     - shared-nw
networks:
  shared-nw:
    name: shared-nw
