version: '3.9'

services:
  leviticus:
    container_name: leviticus
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.development
    ports:
      - 8001:7000
    depends_on:
      - elastic
      - redis
      # - rabbit
    networks:
      - singleNetwork
    env_file:
      - ../.env.docker
    volumes:
      - ../src:/app/src:cached
      - ../prisma:/app/prisma:cached
      - ../input:/app/input:cached
      - ../output:/app/output:cached

  elastic:
    image: elasticsearch:8.1.0
    container_name: elastic
    restart: 'no'
    networks:
      - singleNetwork
    ports:
      - 9400:9200
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - singleNetwork

  # rabbit:
  #   image: rabbitmq:3-management
  #   container_name: rabbit
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   env_file:
  #     - ../.env.docker
  # extreemly slow on mac
  # labels:
  #   image: labels:latest
  #   container_name: labels
  #   # deploy:
  #   #   resources:
  #   #     reservations:
  #   #       devices:
  #   #         - capabilities: [ gpu ]
  #   networks:
  #     - shared-nw
  #   env_file:
  #     - ../.env.labels
  #   ports:
  #     - 8005:8000
  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.2
    ports:
      - "5601:5601"
    networks:
      - singleNetwork
networks:
  singleNetwork:
    name: singleNetwork
