version: '3.9'

services:
  leviticusp:
    container_name: leviticusp
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.production
    ports:
      - 8001:7000
    environment:
      - ELASTIC_PASSWORD=e0F5Ekp9uDHTqBjl0HeinesJ
      - ELASTIC_URL=https://d80c9609865141c58768f3a8590d096e.eu-central-1.aws.cloud.es.io:9243
      - ELASTIC_USERNAME=elastic
      - USERNAME_NEO=neo4j
      - PASSWORD_NEO=E_2a6xQywP75I9GbLWGbkPIrLSFZ_0GjSkci0EgZ5h4
    # depends_on:
    #   - kibana
    # networks:
    #   - shared-nw
    env_file:
      - ../.env.docker
    volumes:
      - ../src:/app/src:cached
      - ../prisma:/app/prisma:cached
      - ../input:/app/input:cached
      - ../output:/app/output:cached
  # kibana:
  #   container_name: kibana
  #   image: docker.elastic.co/kibana/kibana:8.1.0
  #   environment:
  #     SERVER_NAME: localhost
  #     ELASTICSEARCH_URL: http://elasticsearch1:9200/
  #   networks:
  #     - shared-nw
  # networks:
  #   shared-nw:
  #     name: shared-nw
