version: '3.9'

services:
  leviticus:
    container_name: leviticus
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.development
    ports:
      - 8001:7000
    networks:
      - shared-nw
    env_file:
      - ../.env.docker
    volumes:
      - ../src:/app/src:cached
      - ../prisma:/app/prisma:cached
      - ../input:/app/input:cached
      - ../output:/app/output:cached

  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.2
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
networks:
  shared-nw:
    name: shared-nw
