version: '3.9'

services:
  leviticusp:
    container_name: leviticusp
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.production
    ports:
      - 8001:7000
    env_file:
      - ../.env.production
    volumes:
      - ../src:/app/src:cached
      - ../prisma:/app/prisma:cached
      - ../input:/app/input:cached
      - ../output:/app/output:cached
